### ISSUE TITLE
Add the level of access that the GITHUB_TOKEN needs to the README

### ISSUE THREAD

**Issue by kleinjm** [vitalinfo/circleci-cancel-draft#2]
Is this the correct level of permissions?

![image](https://user-images.githubusercontent.com/2565158/117486567-0953bc00-af27-11eb-91c1-d40ef7bbdac6.png)

**Comment by vitalinfo** [comment]
@kleinjm readme has been updated https://github.com/vitalinfo/circleci-cancel-draft/pull/4
